-- 코드를 입력하세요
# SELECT NAME, DATETIME
# FROM ANIMAL_INS I
# OUTER JOIN ANIMAL_OUTS O
# ON I.ANIMAL_ID = O.ANIMAL_ID
# WHERE I.ANIMAL_ID NOT IN O.ANIMAL_ID
# ORDER BY I.DATETIME LIMIT 3;
SELECT I.NAME, I.DATETIME
FROM ANIMAL_INS I
WHERE ANIMAL_ID NOT IN (SELECT ANIMAL_ID FROM ANIMAL_OUTS)
ORDER BY I.DATETIME LIMIT 3;